version: '3.8'

networks:
  aula3_net:
    driver: bridge
volumes:
  db_vol3:
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root@gmail.com
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_DB: test_db
    networks:
      - aula3_net
    ports:
      - 5432:5432
    volumes:
      - db_vol3:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    networks:
      - aula3_net
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rootpwd   
